apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-learning-api-ingress
  namespace: development
spec:
  ingressClassName: nginx
  rules:
    - host: k8s-learning-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-learning-api-service
                port:
                  number: 80
